# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Quartz build

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 22.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout Customized Quartz
      uses: actions/checkout@v4.1.5
      with:
        repository: longman694/LDT-quartz
        ref: LDT
    - name: Checkout content
      # run: git clone --depth 1 git@github.com:longman694/LDN.git content
      uses: actions/checkout@v4.1.5
      with:
        path: content
    - name: Checkout public
      # run: git clone --depth 1 -b gh-pages git@github.com:longman694/LDN.git public
      uses: actions/checkout@v4.1.5
      with:
        repository: ${{ github.repository }}@gh-pages
        path: public
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm exec quartz build
    - name: Push public
      run: cd public && git commit -am "deploy $(date +%Y%m%d-%H%M%S)" && git push
